name: Our Workflow
  
on:
  push:
    branches:
      - "main"

jobs:
  run-tests:
    name: Run JavaScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-nodes@v4
        with: 
          node-version: 20

      - name: Install Dependencies
        run: npm  ci
      - name: Run Tests
        run: npm test